import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Lato, Montserrat } from 'next/font/google';

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato', 
  weight: ['400', '300', '700'], 
  display: 'swap', 
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat', // This creates the CSS variable
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${lato.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
